### ISSUE TITLE
Seeing "ALERT: Could not register permissions" using DatabaseMigrations trait in tests

### ISSUE THREAD

**Issue by mstralka** [spatie/laravel-permission#109]
I am trying to write tests that will use sqlite in-memory and the *DatabaseMigrations* trait but I get this alert in the log for every test:
````
testing.ALERT: Could not register permissions
````

Tracking that down, `PermissionServiceProvider->boot()` calls `$permissionLoader->registerPermissions();`, which then calls `getPermissions()`, and this method is trying to load the `Permission` objects from the database - but the table does not exist yet when the application is being bootstrapped.

If I extend the logging statement in `PermissionRegistrar` to print the exception message:
````
SQLSTATE[HY000]: General error: 1 no such table: permissions (SQL: select * from "permissions")
````

Does anyone have any suggestions for how to use the *DatabaseMigrations* trait with this package in tests?

Thanks

**Comment by mstralka** [comment]
I figured out a workaround, but I don't think I'll be able to use in-memory sqlite.  I created a connection  in *database.php* file like this:
````
'sqlite_testing' => [
        'driver' => 'sqlite',
        'database' => database_path('testing.sqlite'),
        'prefix' => '',
    ]
````

My test class now implements `setUpBeforeClass` like this:

````
public static function setUpBeforeClass()
 {
    parent::setUpBeforeClass();
    $p = new Process('php artisan migrate:refresh --seed --database=sqlite_testing');
    $p->run();
}
````

Then instead of using the *DatabaseMigrations* trait, I use the *DatabaseTransactions* trait.  Doing this eliminates the errors in the log.

Thanks

**Comment by drbyte** [comment]
Have you tried:

```php
use \Illuminate\Support\Facades\Artisan;
```
and then in your `setup` do:
```php
        Artisan::call('migrate');
        Artisan::call('db:seed');
```

**Comment by mstralka** [comment]
Thank you for the suggestion.  I tried that too, but this package's `PermissionServiceProvider` is trying to load the *Permission* objects from the database during the application's bootstrap process.

I can't run `Artisan::call('migrate')` before the application is bootstrapped inside of the parent `setUp()` method, and I can't make it run during the bootstrap process, before `PermissionServiceProvider` is booted.  I could write a custom ServiceProvider and inserted it before `PermissionServiceProvider` in `config/app.php`, but that seems strange.  

So I guess I'll settle for testing against a database on the file system and seed it as noted above.

Thank you

**Comment by nisbeti** [comment]
I am using in :memory: sqlite database for tests and had the same errors, but then I discovered that it was due to having forgotten to run following command 
```php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"```
All works fine now

**Comment by Mahmoudz** [comment]
Same error, here's my output. I think #143 is going to solve this!

```Jekyll
[2016-12-30 14:51:34] testing.ALERT: Could not register permissions
[2016-12-30 14:51:34] testing.ALERT: SQLSTATE[HY000] General error: 1 no such table: permissions (SQL: select * from "permissions")
[2016-12-30 14:51:34] testing.ALERT: #0 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Connection.php(726): Illuminate\Database\Connection->runQueryCallback('select * from "...', Array, Object(Closure))
#1 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Connection.php(351): Illuminate\Database\Connection->run('select * from "...', Array, Object(Closure))
#2 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1648): Illuminate\Database\Connection->select('select * from "...', Array, true)
#3 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1634): Illuminate\Database\Query\Builder->runSelect()
#4 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(636): Illuminate\Database\Query\Builder->get(Array)
#5 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(327): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(77): Illuminate\Database\Eloquent\Builder->get()
#7 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(349): Spatie\Permission\PermissionRegistrar->Spatie\Permission\{closure}()
#8 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(78): Illuminate\Cache\Repository->rememberForever('spatie.permissi...', Object(Closure))
#9 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/spatie/laravel-permission/src/PermissionRegistrar.php(46): Spatie\Permission\PermissionRegistrar->getPermissions()
#10 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php(37): Spatie\Permission\PermissionRegistrar->registerPermissions()
#11 [internal function]: Spatie\Permission\PermissionServiceProvider->boot(Object(Spatie\Permission\PermissionRegistrar))
#12 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#13 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(769): Illuminate\Container\Container->call(Array)
#14 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(752): Illuminate\Foundation\Application->bootProvider(Object(Spatie\Permission\PermissionServiceProvider))
#15 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Spatie\Permission\PermissionServiceProvider), 40)
#16 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(753): array_walk(Array, Object(Closure))
#17 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#18 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#19 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#20 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/app/Port/Tests/PHPUnit/Abstracts/TestCase.php(66): Illuminate\Foundation\Console\Kernel->bootstrap()
#21 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(91): App\Port\Tests\PHPUnit\Abstracts\TestCase->createApplication()
#22 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestCase.php(66): Illuminate\Foundation\Testing\TestCase->refreshApplication()
#23 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/app/Port/Tests/PHPUnit/Abstracts/TestCase.php(33): Illuminate\Foundation\Testing\TestCase->setUp()
#24 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/Framework/TestCase.php(950): App\Port\Tests\PHPUnit\Abstracts\TestCase->setUp()
#25 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/Framework/TestResult.php(701): PHPUnit_Framework_TestCase->runBare()
#26 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/Framework/TestCase.php(909): PHPUnit_Framework_TestResult->run(Object(App\Containers\User\UI\API\Tests\Functional\RegisterUserThatWasNotVisitorTest))
#27 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/Framework/TestSuite.php(728): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#28 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/Framework/TestSuite.php(728): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#29 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(487): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#30 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/TextUI/Command.php(188): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Array, true)
#31 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/src/TextUI/Command.php(118): PHPUnit_TextUI_Command->run(Array, true)
#32 /Users/mz/Codes/Projects/Prints-OMS/Prints-OMS/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#33 {main}
```
