### ISSUE TITLE
Class Permission not found.

### ISSUE THREAD

**Issue by Tjoosten** [spatie/laravel-permission#127]
### Stack trace: 

<details>
```
[2016-09-21 08:48:30] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Permisssion' not found in D:\SIJOT\website\database\seeds\PermissionTableSeeder.php:23
Stack trace:
#0 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Database\Seeder.php(39): PermissionTableSeeder->run()
#1 D:\SIJOT\website\database\seeds\DatabaseSeeder.php(14): Illuminate\Database\Seeder->call('PermissionTable...')
#2 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Database\Console\Seeds\SeedCommand.php(63): DatabaseSeeder->run()
#3 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2280): Illuminate\Database\Console\Seeds\SeedCommand->Illuminate\Database\Console\Seeds\{closure}()
#4 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Database\Console\Seeds\SeedCommand.php(64): Illuminate\Database\Eloquent\Model::unguarded(Object(Closure))
#5 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#6 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Container\Container.php(507): call_user_func_array(Array, Array)
#7 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#8 D:\SIJOT\website\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 D:\SIJOT\website\vendor\symfony\console\Application.php(818): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 D:\SIJOT\website\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 D:\SIJOT\website\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 D:\SIJOT\website\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 D:\SIJOT\website\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 {main}  
```
</details> 

### Seed: 

<details>
```php
<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Illuminate\Support\Facades\DB;

class PermissionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DELETE DATA:
        // -------------
        DB::table('permissions')->delete();

        // INJECT DATA:
        // -------------
        // TEMPLATE: Permisssion::create(['name' => '']);
        Permisssion::create(['name' => 'blocked']);
        Permisssion::create(['name' => 'active']);
    }
}
```
</details>

`composer dump-autoload` won't fix this one.

**Comment by freekmurze** [comment]
Pretty sure this has something to do with your project. The namespace is correct: https://github.com/spatie/laravel-permission/blob/master/src/Models/Permission.php#L3

**Comment by zohaib-zix** [comment]
still have same issue

**Comment by drbyte** [comment]
The only way I can create these symptoms is to:
- forget to actually `composer require spatie/laravel-permission`
- or delete it via composer without cleaning up my code
- or manually mangle the files in the `vendor` directory 
- or any other thing that breaks composer so that autoload isn't working properly

Unfortunately that means whatever is causing `Class Permission not found` is something wrong in your project.
