### ISSUE TITLE
Not working in Lumen 5.8 with latest irazasyed/larasupport v1.7.0

### ISSUE THREAD

**Issue by bojidartonchev** [spatie/laravel-permission#1588]
Hello,

I had the following issue after upgrading both **laravel-permission** and **irazasyed/larasupport** to latest versions.

```
[2020-10-13 08:44:11] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method Laravel\Lumen\Application::configPath() in /var/www-hosts/FondleApi/vendor/irazasyed/larasupport/src/helpers.php:44
Stack trace:
#0 /var/www-hosts/FondleApi/vendor/spatie/laravel-permission/src/PermissionServiceProvider.php(19): config_path()
#1 [internal function]: Spatie\Permission\PermissionServiceProvider->boot()
#2 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(32): call_user_func_array()
#3 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(90): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www-hosts/FondleApi/vendor/illuminate/container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#5 /var/www-hosts/FondleApi/vendor/illuminate/container/Container.php(576): Illuminate\Container\BoundMethod::call()
#6 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(244): Illuminate\Container\Container->call()
#7 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(229): Laravel\Lumen\Application->bootProvider()
#8 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\{closure}()
#9 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Application.php(230): array_walk()
#10 /var/www-hosts/FondleApi/vendor/laravel/lumen-framework/src/Console/Kernel.php(113): Laravel\Lumen\Application->boot()
#11 /var/www-hosts/FondleApi/artisan(35): Laravel\Lumen\Console\Kernel->handle()
#12 {main} {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to undefined method Laravel\\Lumen\\Application::configPath() at /var/www-hosts/FondleApi/vendor/irazasyed/larasupport/src/helpers.php:44)
```

After downgrading **irazasyed/larasupport** to v1.6.0, it is working fine.

Could you please assist me in resolving this?

Best regards.

**Comment by drbyte** [comment]
> local.ERROR: Call to undefined method Laravel\Lumen\Application::configPath() in ... /vendor/irazasyed/larasupport/src/helpers.php:44

The error points to what appears to be a bug in the larasupport package.

Looks like they added a `config_path` helper function that calls a method that doesn't exist in Lumen.
https://github.com/irazasyed/larasupport/commit/2935fc583641338be3e900b7add8f646332f3a8c#diff-7827dcf8c28ba9d97397f03b4ca75c132540f5c377e253fbc47ef064a373ce73

https://github.com/laravel/lumen-framework/blob/05ea83d0cd073a9b7954035a6eafee0c265e9293/src/Application.php#L692-L719
