### ISSUE TITLE
Doesn't seem to add methods to users table

### ISSUE THREAD

**Issue by benyanke** [spatie/laravel-permission#477]
I've installed it as found on the Readme, and I'm still having trouble connecting.

Ideas?

User model:
```
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
[...]
```

Test code:
```php
print_r($user->getAllPermissions());
```
(Also occurs with things like `$user->assignRole()`)

Log:
```
[2017-09-26 17:03:26] local.ERROR: BadMethodCallException: Method getAllPermissions does not exist. in /var/www/laravel/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /var/www/laravel/app/Console/Commands/AssignDefaultPermissions.php(140): Illuminate\Support\Collection->__call('getAllPermissio...', Array)
#1 [internal function]: App\Console\Commands\AssignDefaultPermissions->handle()
#2 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#7 /var/www/laravel/vendor/symfony/console/Command/Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#8 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /var/www/laravel/vendor/symfony/console/Application.php(888): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/laravel/vendor/symfony/console/Application.php(224): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\AssignDefaultPermissions), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/laravel/vendor/symfony/console/Application.php(125): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/laravel/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 {main}  

```

**Comment by drbyte** [comment]
What version of Laravel?

**Comment by drbyte** [comment]
> [2017-09-26 17:03:26] local.ERROR: BadMethodCallException: Method getAllPermissions does not exist. in /vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php:74
Stack trace:
#0 /app/Console/Commands/AssignDefaultPermissions.php(140): Illuminate\Support\Collection->__call('getAllPermissio...', Array)


Please post your `/app/Console/Commands/AssignDefaultPermissions.php` contents.

**Comment by benyanke** [comment]
Version 5.4.

I will post the full code tomorrow when I get back to work, but the test code I mentioned above is the notable part of the `AssignDefaultPermissions.php`. The rest is just wrapper code to make it an artisan command. I'm early enough along I'm just only using a line or two of the permission code while I'm developing.

**Comment by introwit** [comment]
@benyanke Hi Ben :) Where are you printing `$user->getAllPermissions()` ?

**Comment by benyanke** [comment]
I'm sorry, I forgot to close the ticket - I believe I got it all working. Not sure what the issue was in the end, I ended up destroying the branch, and following the Readme implementation steps again. I assume I had missed a step or something trivial.

This library is quite useful, expect a postcard at the end of the year when this goes to prod.
