### ISSUE TITLE
Lumen: Class 'Memcached' not found : Seems to randomly look for a SPECIFIC cache driver

### ISSUE THREAD

**Issue by Wintereise** [spatie/laravel-permission#611]
Hi,

In my `.env` file, my CACHE_DRIVER is set to `file`. Lumen itself respects this just fine.

However, this package seems to look for a specific driver (Memcached in my case). This error does not happen on every request, seems to only occur when the cache is attempted to be updated

Full stack trace below:

```php
[2017-12-29 04:47:38] lumen.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Memcached' not found in G:\project\vendor\illuminate\cache\MemcachedConnector.php:69
Stack trace:
#0 G:\project\vendor\illuminate\cache\MemcachedConnector.php(48): Illuminate\Cache\MemcachedConnector->createMemcachedInstance(NULL)
#1 G:\project\vendor\illuminate\cache\MemcachedConnector.php(21): Illuminate\Cache\MemcachedConnector->getMemcached(NULL, Array, Array)
#2 G:\project\vendor\illuminate\cache\CacheManager.php(171): Illuminate\Cache\MemcachedConnector->connect(Array, NULL, Array, Array)
#3 G:\project\vendor\illuminate\cache\CacheManager.php(105): Illuminate\Cache\CacheManager->createMemcachedDriver(Array)
#4 G:\project\vendor\illuminate\cache\CacheManager.php(80): Illuminate\Cache\CacheManager->resolve('memcached')
#5 G:\project\vendor\illuminate\cache\CacheManager.php(58): Illuminate\Cache\CacheManager->get('memcached')
#6 G:\project\vendor\illuminate\cache\CacheManager.php(69): Illuminate\Cache\CacheManager->store('memcached')
#7 G:\project\vendor\illuminate\cache\CacheServiceProvider.php(28): Illuminate\Cache\CacheManager->driver()
#8 G:\project\vendor\illuminate\container\Container.php(749): Illuminate\Cache\CacheServiceProvider->Illuminate\Cache\{closure}(Object(Laravel\Lumen\Application), Array)
#9 G:\project\vendor\illuminate\container\Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#10 G:\project\vendor\illuminate\container\Container.php(586): Illuminate\Container\Container->resolve('cache.store', Array)
#11 G:\project\vendor\laravel\lumen-framework\src\Application.php(230): Illuminate\Container\Container->make('cache.store', Array)
#12 G:\project\vendor\laravel\lumen-framework\src\Application.php(589): Laravel\Lumen\Application->make('cache.store')
#13 G:\project\vendor\laravel\lumen-framework\src\Application.php(294): Laravel\Lumen\Application->loadComponent('cache', 'Illuminate\\Cach...', 'cache.store')
#14 G:\project\vendor\illuminate\container\Container.php(749): Laravel\Lumen\Application->Laravel\Lumen\{closure}(Object(Laravel\Lumen\Application), Array)
#15 G:\project\vendor\illuminate\container\Container.php(631): Illuminate\Container\Container->build(Object(Closure))
#16 G:\project\vendor\illuminate\container\Container.php(586): Illuminate\Container\Container->resolve('cache.store', Array)
#17 G:\project\vendor\laravel\lumen-framework\src\Application.php(230): Illuminate\Container\Container->make('cache.store', Array)
#18 G:\project\vendor\illuminate\container\Container.php(885): Laravel\Lumen\Application->make('cache.store')
#19 G:\project\vendor\illuminate\container\Container.php(813): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#20 G:\project\vendor\illuminate\container\Container.php(780): Illuminate\Container\Container->resolveDependencies(Array)
#21 G:\project\vendor\illuminate\container\Container.php(631): Illuminate\Container\Container->build('Spatie\\Permissi...')
#22 G:\project\vendor\illuminate\container\Container.php(586): Illuminate\Container\Container->resolve('Spatie\\Permissi...', Array)
#23 G:\project\vendor\laravel\lumen-framework\src\Application.php(230): Illuminate\Container\Container->make('Spatie\\Permissi...', Array)
#24 G:\project\vendor\illuminate\container\BoundMethod.php(156): Laravel\Lumen\Application->make('Spatie\\Permissi...')
#25 G:\project\vendor\illuminate\container\BoundMethod.php(116): Illuminate\Container\BoundMethod::addDependencyForCallParameter(Object(Laravel\Lumen\Application), Object(ReflectionParameter), Array, Array)
#26 G:\project\vendor\illuminate\container\BoundMethod.php(29): Illuminate\Container\BoundMethod::getMethodDependencies(Object(Laravel\Lumen\Application), Array, Array)
#27 G:\project\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 G:\project\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#29 G:\project\vendor\illuminate\container\Container.php(549): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#30 G:\project\vendor\laravel\lumen-framework\src\Application.php(197): Illuminate\Container\Container->call(Array)
#31 G:\project\bootstrap\app.php(94): Laravel\Lumen\Application->register(Object(Spatie\Permission\PermissionServiceProvider))
#32 G:\project\public\index.php(14): require('G:\\Spectero\\mar...')
#33 {main} 
```

I haven't really tried to use it yet, have only installed it and added the `HasRoles` trait to one of my models. That's it.

**Comment by drbyte** [comment]
@benjamincrozat  ... Here's another Lumen scenario you may have more insight into than I do.

**Comment by benjamincrozat** [comment]
This package is probably not responsible for this. For now, I don't see anything in the code that enforces the Memcached driver.

**Comment by drbyte** [comment]
Those are my thoughts as well.  It feels like something within the application, which may only be surfacing because this package uses the cache, whereas the application may have no other reason to.

**Comment by Wintereise** [comment]
Hi @drbyte @benjamincrozat The cache itself functions just fine otherwise.

I can write values into it and then read them out in other requests, no problems. I'll try to isolate it into a bare repository and get back to you after new years.

Thanks.

**Comment by Wintereise** [comment]
Hi team,

So, weirdly enough, this only seems to happen with Apache and DSO PHP.

nginx+fpm, or even the built in PHP webserver does not run into it. I'll assume it's something wrong with my DSO PHP env and close this out. Sorry for the noise.
