### ISSUE TITLE
Exception when remove role from a user

### ISSUE THREAD

**Issue by HamzaDevz** [spatie/laravel-permission#845]
I'm running in : 
- PHP 7.2.4
- Laravel 5.4
- Laravel-permission 2.17.0

When i assign a role to a user all is good but when i try to remove it i got this awful exception,

```
{
    "errors": {
        "message": "count(): Parameter must be an array or an object that implements Countable",
        "status_code": 500,
        "exception": "ErrorException",
        "trace": [
            "#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'count(): Parame...', '/var/www/api-v1...', 352, Array)",
            "#1 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Concerns/InteractsWithPivotTable.php(352): count(1)",
            "#2 /var/www/api-v1/vendor/spatie/laravel-permission/src/Traits/HasRoles.php(115): Illuminate\\Database\\Eloquent\\Relations\\BelongsToMany->detach(1)",
            "#3 /var/www/api-v1/app/Http/Controllers/Api/RoleController.php(56): App\\User->removeRole('provider')",
            "#4 [internal function]: App\\Http\\Controllers\\Api\\RoleController->removeRole(Object(Illuminate\\Http\\Request), '1')",
            "#5 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)",
            "#6 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('removeRole', Array)",
            "#7 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Api\\RoleController), 'removeRole')",
            "#8 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\\Routing\\Route->runController()",
            "#9 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(559): Illuminate\\Routing\\Route->run()",
            "#10 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#11 /var/www/api-v1/vendor/spatie/laravel-permission/src/Middlewares/RoleMiddleware.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#12 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Spatie\\Permission\\Middlewares\\RoleMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'super-admin')",
            "#13 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#14 /var/www/api-v1/app/Http/Middleware/AuthenticateWithJWT.php(50): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#15 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\\Http\\Middleware\\AuthenticateWithJWT->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#16 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#17 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#18 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#19 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#20 /var/www/api-v1/vendor/barryvdh/laravel-cors/src/HandleCors.php(36): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#21 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#22 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#23 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#24 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(561): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#25 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(520): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))",
            "#26 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(498): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))",
            "#27 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(174): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))",
            "#28 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))",
            "#29 /var/www/api-v1/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(38): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#30 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#31 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#32 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#33 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#34 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#35 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#36 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#37 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#38 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#39 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#40 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#41 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#42 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))",
            "#43 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#44 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#45 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#46 /var/www/api-v1/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#47 /var/www/api-v1/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#48 {main}"
        ]
    }
}
```

do anyone have an idea ?

**Comment by drbyte** [comment]
Hmmmm.

I tried replicating the problem using a tinker session in a [basic demo app](https://github.com/drbyte/spatie-permissions-demo) I have for this package, and get no error on `removeRole()`:

PHP 7.2.8
Laravel 5.5.42
Permissions v2.17.0

```
tinker
Psy Shell v0.9.7 (PHP 7.3.0beta2 — cli) by Justin Hileman
>>> $user = App\User::first();
=> App\User {#2894
     id: 4,
     name: "Vernie Runte",
     email: "wintheiser.eloy@example.com",
     created_at: "2018-08-04 03:21:55",
     updated_at: "2018-08-04 03:21:55",
   }
>>> $user->fresh()->roles;
=> Illuminate\Database\Eloquent\Collection {#2899
     all: [],
   }
>>> $user->assignRole('author');
=> App\User {#2894
     id: 4,
     name: "Vernie Runte",
     email: "wintheiser.eloy@example.com",
     created_at: "2018-08-04 03:21:55",
     updated_at: "2018-08-04 03:21:55",
   }
>>> $user->fresh()->roles;
=> Illuminate\Database\Eloquent\Collection {#2908
     all: [
       Spatie\Permission\Models\Role {#2904
         id: 8,
         name: "author",
         guard_name: "web",
         created_at: "2018-08-04 03:21:55",
         updated_at: "2018-08-04 03:21:55",
         pivot: Illuminate\Database\Eloquent\Relations\MorphPivot {#2902
           model_id: 4,
           role_id: 8,
         },
       },
     ],
   }
>>> $user->removeRole('author');
=> null
>>> $user->fresh()->roles;
=> Illuminate\Database\Eloquent\Collection {#2897
     all: [],
   }
```

I'd be curious about what your model does differently than this simple demo app at https://github.com/drbyte/spatie-permissions-demo

**Comment by waleedakhlaq** [comment]
You can use syncRole function instead of assignRole. syncRole will automatically delete the previous roles assigned to user and assigned the new ones. 

$user->syncRoles($roles)

**Comment by IAmShafqatAli** [comment]
@waleedakhlaq Thank you so much, your proposed solution worked like a charm .

Cheers.
