### ISSUE TITLE
Issue assigning permission to roles

### ISSUE THREAD

**Issue by mathewparet** [spatie/laravel-permission#928]
I am unable to assign permissions to role. I just did a fresh installation and created the below DatabaseSeeder:

```
<?php

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class InitialRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Reset cached roles and permissions
        app()['cache']->forget('spatie.permission.cache');

        // create permissions
        Permission::create(['name' => 'User: View']);
        Permission::create(['name' => 'User: Delete']);
        Permission::create(['name' => 'User: Delete Own Account']);
        Permission::create(['name' => 'User: Update Others Profile']);
        Permission::create(['name' => 'User: Update Roles']);
        Permission::create(['name' => 'User: Suspend']);
        Permission::create(['name' => 'User: Force Verify']);
        Permission::create(['name' => 'User: Impersonate']);
        Permission::create(['name' => 'User: View Roles']);

        Permission::create(['name' => 'Role: View']);
        Permission::create(['name' => 'Role: Manage']);

        // create roles and assign created permissions

        $role = Role::create(['name' => 'User']);
        $role->givePermissionTo('User: Delete Own Account');

        $role = Role::create(['name' => 'Staff Basic']);
        $role->givePermissionTo(['User: View','User: View Roles','Role: View']);

        $role = Role::create(['name' => 'Manage Users']);
        $role->givePermissionTo(['User: Delete','User: Update Others Profile', 'User: Update Roles', 'User: Suspend', 'User: Force Verify']);

        $role = Role::create(['name' => 'Manage Roles']);
        $role->givePermissionTo('Role: Manage');
    }
}

```

When I run the seeder, I get the below exception:
```

[2018-11-10 04:36:04] local.ERROR: There is no permission named `User: Delete Own Account` for guard `web`. {"exception":"[object] (Spatie\\Permission\\Exceptions\\PermissionDoesNotExist(code: 0): There is no permission named `User: Delete Own Account` for guard `web`. at /Users/mathewparet/Projects/harvest/vendor/spatie/laravel-permission/src/Exceptions/PermissionDoesNotExist.php:11)
[stacktrace]
#0 /Users/mathewparet/Projects/harvest/vendor/spatie/laravel-permission/src/Models/Permission.php(96): Spatie\\Permission\\Exceptions\\PermissionDoesNotExist::create('User: Delete Ow...', 'web')
#1 /Users/mathewparet/Projects/harvest/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(362): Spatie\\Permission\\Models\\Permission::findByName('User: Delete Ow...', 'web')
#2 /Users/mathewparet/Projects/harvest/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(285): Spatie\\Permission\\Models\\Role->getStoredPermission('User: Delete Ow...')
#3 [internal function]: Spatie\\Permission\\Models\\Role->Spatie\\Permission\\Traits\\{closure}('User: Delete Ow...', 0)
#4 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1011): array_map(Object(Closure), Array, Array)
#5 /Users/mathewparet/Projects/harvest/vendor/spatie/laravel-permission/src/Traits/HasPermissions.php(286): Illuminate\\Support\\Collection->map(Object(Closure))
#6 /Users/mathewparet/Projects/harvest/database/seeds/InitialRoleSeeder.php(36): Spatie\\Permission\\Models\\Role->givePermissionTo('User: Delete Ow...')
#7 [internal function]: InitialRoleSeeder->run()
#8 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#9 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(122): Illuminate\\Container\\Container->call(Array)
#13 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(63): Illuminate\\Database\\Seeder->__invoke()
#14 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/GuardsAttributes.php(122): Illuminate\\Database\\Console\\Seeds\\SeedCommand->Illuminate\\Database\\Console\\Seeds\\{closure}()
#15 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(64): Illuminate\\Database\\Eloquent\\Model::unguarded(Object(Closure))
#16 [internal function]: Illuminate\\Database\\Console\\Seeds\\SeedCommand->handle()
#17 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#18 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#19 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#20 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#21 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#22 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#23 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
#24 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#25 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Seeds\\SeedCommand), Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#26 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#27 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#28 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Application.php(188): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\BufferedOutput))
#29 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(250): Illuminate\\Console\\Application->call('db:seed', Array, NULL)
#30 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(223): Illuminate\\Foundation\\Console\\Kernel->call('db:seed', Array)
#31 /Users/mathewparet/Projects/harvest/database/migrations/2018_11_09_163915_create_permission_tables.php(84): Illuminate\\Support\\Facades\\Facade::__callStatic('call', Array)
#32 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(404): CreatePermissionTables->up()
#33 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Connection.php(528): Illuminate\\Database\\Migrations\\Migrator->Illuminate\\Database\\Migrations\\{closure}(Object(Illuminate\\Database\\MySqlConnection))
#34 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Connection.php(556): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#35 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Connection.php(533): Illuminate\\Database\\Connection->withFreshQueryLog(Object(Closure))
#36 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(406): Illuminate\\Database\\Connection->pretend(Object(Closure))
#37 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(379): Illuminate\\Database\\Migrations\\Migrator->getQueries(Object(CreatePermissionTables), 'up')
#38 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(173): Illuminate\\Database\\Migrations\\Migrator->pretendToRun(Object(CreatePermissionTables), 'up')
#39 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(147): Illuminate\\Database\\Migrations\\Migrator->runUp('/Users/mathewpa...', 2, true)
#40 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(96): Illuminate\\Database\\Migrations\\Migrator->runPending(Array, Array)
#41 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(71): Illuminate\\Database\\Migrations\\Migrator->run(Array, Array)
#42 [internal function]: Illuminate\\Database\\Console\\Migrations\\MigrateCommand->handle()
#43 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#44 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#45 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#46 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#47 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#48 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#49 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#50 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#51 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Database\\Console\\Migrations\\MigrateCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#52 /Users/mathewparet/Projects/harvest/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#53 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#54 /Users/mathewparet/Projects/harvest/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#55 /Users/mathewparet/Projects/harvest/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#56 {main}
"} 

```

I investigated and confirmed that in fact, roles & permissions are being created. However, models/Permission.php ```findByName``` isn't able to identify the permission. 

My default guard is web.

**Comment by mathewparet** [comment]
I am using Laravel 5.7

**Comment by drbyte** [comment]
I suspect something wrong in your app. 
I just created a fresh application using Laravel 5.7, added your seeder plus some dump() statements to show that the seeder works, and it works without errors:

```sh
shell> ~/Sites > laravel new seedtest
Crafting application...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 72 installs, 0 updates, 0 removals
//
Application ready! Build something amazing.
shell> ~/Sites > cd seedtest
shell> ~/Sites/seedtest > a make:auth
Authentication scaffolding generated successfully.
shell> ~/Sites/seedtest > composer require spatie/laravel-permission
Using version ^2.25 for spatie/laravel-permission
  - Installing spatie/laravel-permission (2.25.0): Loading from cache
Package manifest generated successfully.
shell> ~/Sites/seedtest > cp .env.example .env
shell> ~/Sites/seedtest > subl .env #specified db=sqlite
shell> ~/Sites/seedtest > touch database/database.sqlite
shell> ~/Sites/seedtest > a vendor:publish
Copied File [/vendor/spatie/laravel-permission/config/permission.php] To [/config/permission.php]
Copied File [/vendor/spatie/laravel-permission/database/migrations/create_permission_tables.php.stub] To [/database/migrations/2018_11_10_053446_create_permission_tables.php]
Publishing complete.
shell> ~/Sites/seedtest > a make:seeder InitialRoleSeeder
Seeder created successfully.
shell> ~/Sites/seedtest > subl database/seeds/InitialRoleSeeder.php ## pasted in code posted by @matheparet and added dump statements
shell> ~/Sites/seedtest > subl database/seeds/DatabaseSeeder.php  ## specified InitialRoleSeeder as the class to run
shell> ~/Sites/seedtest > a migrate:fresh --seed
Dropped all tables successfully.
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2018_11_10_053446_create_permission_tables
Migrated:  2018_11_10_053446_create_permission_tables
Seeding: InitialRoleSeeder
Illuminate\Support\Collection {#836
  #items: array:4 [
    "User" => "web"
    "Staff Basic" => "web"
    "Manage Users" => "web"
    "Manage Roles" => "web"
  ]
}
Illuminate\Support\Collection {#860
  #items: array:11 [
    "User: View" => "web"
    "User: Delete" => "web"
    "User: Delete Own Account" => "web"
    "User: Update Others Profile" => "web"
    "User: Update Roles" => "web"
    "User: Suspend" => "web"
    "User: Force Verify" => "web"
    "User: Impersonate" => "web"
    "User: View Roles" => "web"
    "Role: View" => "web"
    "Role: Manage" => "web"
  ]
}
Database seeding completed successfully.
```

Here's the code I added to your seeder:

```diff
class InitialRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
//
//
//
        $role = Role::create(['name' => 'Manage Roles']);
        $role->givePermissionTo('Role: Manage');

+        $roles = Role::all()->pluck('guard_name', 'name');
+        $permissions = Permission::all()->pluck('guard_name', 'name');
+        dump($roles ,$permissions);
    }
}
```

I suspect something else in your app is conflicting.

**Comment by mathewparet** [comment]
I found the scenario where this is occurring. I got a clue from your execution where you used ```php artisan migrate:fresh```

When I did it, it worked! 

But after that, I created a user account so that the users table is populated and then tried adding more roles and permissions it throws the same error. Somehow, it is working only when the users table is empty.

My users table has only 1 extra field - suspended which stores 1 or 0 to indicate whether the account is suspended. I also use the email verification feature provided by Laravel 5.7, so the email_verified_at field was also populated.

**Comment by mathewparet** [comment]
It might sound weared. After trying the same thing a couple of times it is working fine now. I can't explain how or why. Thanks anyways.
