### ISSUE TITLE
i can not require this package using composer

### ISSUE THREAD

**Issue by jafar690** [spatie/laravel-permission#945]
here is the error i get
```

 composer require spatie/laravel-permission

Using version ^2.26 for spatie/laravel-permission
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing spatie/laravel-permission (2.26.1): Loading from cache
    Failed to execute unzip -qq  '/home/kjafar690/projects/myNextProject/vendor/spatie/laravel-permission/f18f1b5e70ddf87e26bb35c957123856' -d '/home/kjafar690/projects/myNextProject/vendor/composer/e14e0b19'

[/home/kjafar690/projects/myNextProject/vendor/spatie/laravel-permission/f18f1b5e70ddf87e26bb35c957123856]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /home/kjafar690/projects/myNextProject/vendor/spatie/laravel-permission/f18f1b5e70ddf87e26bb35c957123856 or
        /home/kjafar690/projects/myNextProject/vendor/spatie/laravel-permission/f18f1b5e70ddf87e26bb35c957123856.zip, and cannot find /home/kjafar690/projects/myNextProject/vendor/spatie/laravel-permission/f18f1b5e70ddf87e26bb35c957123856.ZIP, period.

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
PHP Warning:  Uncaught ErrorException: require(/home/kjafar690/projects/myNextProject/vendor/composer/../spatie/laravel-permission/src/helpers.php): failed to open stream: No such file or directory in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php:66
Stack trace:
#0 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/k...', '/home/kjafar690...', 66, Array)
#1 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(66): require()
#2 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(56): composerRequireb1c55f2d0268820964aa41c767194782('377b22b161c09ed...', '/home/kjafar690...')
#3 /home/kjafar690/projects/myNextProject/vendor/autoload.php(7): ComposerAutoloaderInitb1c55f2d0268820964aa41c767194782::getLoader()
#4 /home/kjafar690/projects/myNextProject/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/home/kjafar690...')
#5 phar:///usr/local/bi in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php on line 66

Warning: Uncaught ErrorException: require(/home/kjafar690/projects/myNextProject/vendor/composer/../spatie/laravel-permission/src/helpers.php): failed to open stream: No such file or directory in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php:66
Stack trace:
#0 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(66): Composer\Util\ErrorHandler::handle(2, 'require(/home/k...', '/home/kjafar690...', 66, Array)
#1 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(66): require()
#2 /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php(56): composerRequireb1c55f2d0268820964aa41c767194782('377b22b161c09ed...', '/home/kjafar690...')
#3 /home/kjafar690/projects/myNextProject/vendor/autoload.php(7): ComposerAutoloaderInitb1c55f2d0268820964aa41c767194782::getLoader()
#4 /home/kjafar690/projects/myNextProject/vendor/laravel/framework/src/Illuminate/Foundation/ComposerScripts.php(30): require_once('/home/kjafar690...')
#5 phar:///usr/local/bi in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  composerRequireb1c55f2d0268820964aa41c767194782(): Failed opening required '/home/kjafar690/projects/myNextProject/vendor/composer/../spatie/laravel-permission/src/helpers.php' (include_path='.:/usr/share/php') in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php on line 66

Fatal error: composerRequireb1c55f2d0268820964aa41c767194782(): Failed opening required '/home/kjafar690/projects/myNextProject/vendor/composer/../spatie/laravel-permission/src/helpers.php' (include_path='.:/usr/share/php') in /home/kjafar690/projects/myNextProject/vendor/composer/autoload_real.php on line 66

```
it seems like an error on your end

**Comment by fullstackfool** [comment]
@jafar690, what version of Laravel/Lumen are you using?

Does `composer clearcache` help at all?

**Comment by jafar690** [comment]
@fullstackfool i solved this by clearing my composer cache and using an old version of this package.
`composer clear-cache`
